// Use the generated Prisma client when a custom output folder is configured.
// This avoids issues where `@prisma/client` resolves to a different client/runtime
// than the one generated by `prisma generate` (common in test runners like Jest).
import path from "path";
import { PrismaClient as GeneratedPrismaClient } from "../generated/prisma/index.js";

export const prisma = new GeneratedPrismaClient();
